spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/mydb
#      host: localhost
#      port: 27017
#      database: mydb
#      username: admin
#      password: password
#      authentication-database: admin


otel:
  traces:
    exporter: otlp
  export:
    otlp:
      protocol: http
      host: jaeger-303ada4c-4478-49dd-b427-8c482bfc17b8
      port: 443
      headers:
        Authorization: Bearer your-token    

logging:
  level:
    io.opentelemetry: DEBUG
    org.springframework.boot.env: DEBUG
    org.springframework.context: DEBUG

---
spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      uri: ${vcap.services.mongodb-service.credentials.uri}
#      OTEL_SERVICE_NAME: 'graal-native-example-app'
#      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://collector:4318'
---
spring:
  config:
    activate:
      on-profile: k8s
  data:
    mongodb:
      uri: ${vcap.services.mongodb-service.credentials.uri}
