# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-probe-config
data:
  application.properties: |
    spring.profiles.active=k8s
    
    spring.ssl.bundle.pem.mongodb-ssl-bundle.reload-on-update=true
    spring.ssl.bundle.pem.mongodb-ssl-bundle.truststore.certificate=file:/workspace/config/{{ .Values.mongodb.tlsSecretCaKey }}
    #spring.ssl.bundle.pem.mongodb-ssl-bundle.keystore.private-key=file:/workspace/config/...    
    
    spring.data.mongodb.uri={{ .Values.mongodb.uri }}
    spring.data.mongodb.ssl.enabled=true
    spring.data.mongodb.ssl.bundle=mongodb-ssl-bundle
    
    otel.logs.exporter=none
    otel.metrics.exporter=none
    
    otel.exporter.otlp.endpoint={{ .Values.otlp.tracing.endpoint }}
    otel.service.name={{ .Values.otlp.serviceName }}
    spring.application.name={{ .Values.otlp.serviceName }}
