# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-probe-config
data:
  application.properties: |
    spring.profiles.active=k8s
    
    spring.ssl.bundle.pem.mongodb-ssl-bundle.reload-on-update=false
    
    {{- with .Values.mongodb.tlsCa }}
    spring.ssl.bundle.pem.mongodb-ssl-bundle.truststore.certificate=file:/workspace/config/tls/{{ . }}
    {{- end }}
    
#    {{- with .Values.mongodb.tlsCert }}
#    spring.ssl.bundle.pem.mongodb-ssl-bundle.truststore.certificate=file:/workspace/config/tls/{{ . }}    
#    {{- end }}
#
#    {{- with .Values.mongodb.tlsKey }}
#    spring.ssl.bundle.pem.mongodb-ssl-bundle.truststore.private-key=file:/workspace/config/tls/{{ . }}    
#    {{- end }}


    {{- with .Values.mongodb.tlsCert }}
    spring.ssl.bundle.pem.mongodb-ssl-bundle.keystore.certificate=file:/workspace/config/tls/{{ . }}
    {{- end }}
    
    {{- with .Values.mongodb.tlsKey }}
    spring.ssl.bundle.pem.mongodb-ssl-bundle.keystore.private-key=file:/workspace/config/tls/{{ . }}
    {{- end }}
    
    
    
    
    spring.data.mongodb.ssl.enabled=true
    spring.data.mongodb.ssl.bundle=mongodb-ssl-bundle

    {{- with .Values.mongodb.uri }}
    spring.data.mongodb.uri={{ . }}
    {{- end }}
    
    spring.data.mongodb.host={{ .Values.mongodb.host }}
    spring.data.mongodb.port={{ .Values.mongodb.port }}
    spring.data.mongodb.username={{ .Values.mongodb.username }}
    spring.data.mongodb.password={{ .Values.mongodb.password }}
    spring.data.mongodb.database={{ .Values.mongodb.database }}
    
    otel.logs.exporter=none
    otel.metrics.exporter=none
    
    otel.exporter.otlp.endpoint={{ .Values.otlp.tracing.endpoint }}
    otel.service.name={{ .Values.otlp.serviceName }}
    spring.application.name={{ .Values.otlp.serviceName }}

    logging.level.org.springframework.boot.autoconfigure.ssl=debug
    logging.level.org.springframework.boot.ssl=debug
    logging.level.org.mongodb=debug
    logging.level.org.springframework.data.mongodb=debug