# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-probe-config
data:
  application.properties: |
    spring.profiles.active=k8s
    spring.data.mongodb.uri={{ .Values.mongodb.uri }}
    otel.logs.exporter=none
    otel.metrics.exporter=none
    
    otel.exporter.otlp.endpoint={{ .Values.otlp.tracing.endpoint }}
    otel.service.name={{ .Values.otlp.tracing.endpoint }}
    spring.application.name={{ .Values.otlp.serviceName }}

