apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-mongo-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "spring-mongo-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-mongo-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: SPRING_DATA_MONGODB_PORT
              value: "{{ .Values.mongodb.port }}"
